### PR TITLE
Use Jinja2 template for creating objects

### PR DESCRIPTION
**Pull request by jleach**
Switched from `api create` with JSON to `api import` with YAML; the yaml is a processed Jinja2 template. This fixes issue #252.

I also switched the name UUID to use hex rather than base64 to avoid punctuation and fixed an issue with the CRD `listKind` property.

### CODE REVIEW

**Comment by stewartshea** [comment]
@jleach tested again; looks like it's still missing the proper namespace prefix on $namespace: 
image

The actual namespace in this case is `$namespace=/bcgov/test/lab-pathfinder-091719-01/devops-platform-security`


Separately, seeing this error on the playbook with the policy lookup: 
```

TASK [Generate policy ID] ******************************************************
--
  | task path: /opt/ansible/playbook.yaml:11
  | changed: [localhost] => {"changed": true, "cmd": ["openssl", "rand", "-hex", "6"], "delta": "0:00:04.704243", "end": "2019-09-18 15:45:45.931071", "rc": 0, "start": "2019-09-18 15:45:41.226828", "stderr": "", "stderr_lines": [], "stdout": "ccf68dc36833", "stdout_lines": ["ccf68dc36833"]}
  |  
  | TASK [Extract variables] *******************************************************
  | task path: /opt/ansible/playbook.yaml:14
  | ok: [localhost] => {"ansible_facts": {"metadata": {"annotations": {"kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"secops.pathfinder.gov.bc.ca/v1alpha1\",\"kind\":\"NetworkSecurityPolicy\",\"metadata\":{\"annotations\":{},\"name\":\"inter-namespace-comms\",\"namespace\":\"devops-platform-security\"},\"spec\":{\"action\":\"Allow\",\"description\":\"allow devops-platform-security to talk to itself\\n\",\"destination\":\"devops-platform-security\",\"source\":\"devops-platform-security\"}}\n"}, "creationTimestamp": "2019-09-18T15:35:42Z", "finalizers": ["finalizer.secops.pathfinder.gov.bc.ca"], "generation": 1, "name": "inter-namespace-comms", "namespace": "devops-platform-security", "resourceVersion": "374281554", "selfLink": "/apis/secops.pathfinder.gov.bc.ca/v1alpha1/namespaces/devops-platform-security/secopspolicies/inter-namespace-comms/status", "uid": "f96861e8-da29-11e9-a3d8-00505683b471"}, "puid": "ccf68dc36833", "spec": {"action": "Allow", "description": "allow devops-platform-security to talk to itself\n", "destination": "devops-platform-security", "source": "devops-platform-security"}}, "changed": false}
  |  
  | TASK [Policy Lookup] ***********************************************************
  | task path: /opt/ansible/lookup_netpol.yaml:10
  | changed: [localhost] => {"changed": true, "cmd": "/usr/local/bin/apoctl api list networkaccesspolicies --namespace \"/bcgov/test/lab-pathfinder-091719-01/devops-platform-security\" --filter \"associatedTags contains k8s-uuid=f96861e8-da29-11e9-a3d8-00505683b471\" -c ID,name", "delta": "0:00:05.528724", "end": "2019-09-18 15:45:53.263140", "rc": 0, "start": "2019-09-18 15:45:47.734416", "stderr": "", "stderr_lines": [], "stdout": "- ID: 5d824fc8311ddc0001471dfa\n  name: inter-ns-network-214532d778c7", "stdout_lines": ["- ID: 5d824fc8311ddc0001471dfa", "  name: inter-ns-network-214532d778c7"]}
  |  
  | TASK [Extract Policy ID] *******************************************************
  | task path: /opt/ansible/lookup_netpol.yaml:19
  | fatal: [localhost]: FAILED! => {"msg": "The conditional check 'output.stdout != \"\" and output.stdout \| from_json \| list \| length > 0' failed. The error was: No JSON object could be decoded\n\nThe error appears to have been in '/opt/ansible/lookup_netpol.yaml': line 19, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  register: output\n- name: Extract Policy ID\n  ^ here\n"}
  |  
  | PLAY RECAP *********************************************************************
  | localhost                  : ok=3    changed=2    unreachable=0    failed=1


```

**Comment by jleach** [comment]
@stewartshea Fixed the path prefix issue and refactored the variable extraction logic to get rid of the error. It works for me so if it fails for you I'll need your policy file to test if that is causing the issue.

**Comment by stewartshea** [comment]
@jleach the namespace change works well, thanks. Update is still breaking... 

Here's the output: 
```

TASK [Generate policy ID] ******************************************************
--
  | task path: /opt/ansible/playbook.yaml:11
  | changed: [localhost] => {"changed": true, "cmd": ["openssl", "rand", "-hex", "6"], "delta": "0:00:05.487190", "end": "2019-09-18 20:34:04.234998", "rc": 0, "start": "2019-09-18 20:33:58.747808", "stderr": "", "stderr_lines": [], "stdout": "e5bc6fbf58e6", "stdout_lines": ["e5bc6fbf58e6"]}
  |  
  | TASK [Extract variables] *******************************************************
  | task path: /opt/ansible/playbook.yaml:14
  | ok: [localhost] => {"ansible_facts": {"metadata": {"annotations": {"kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"secops.pathfinder.gov.bc.ca/v1alpha1\",\"kind\":\"NetworkSecurityPolicy\",\"metadata\":{\"annotations\":{},\"name\":\"inter-namespace-comms\",\"namespace\":\"devops-platform-security\"},\"spec\":{\"action\":\"Allow\",\"description\":\"allow devops-platform-security to talk to itself\\n\",\"destination\":\"devops-platform-security\",\"source\":\"devops-platform-security\"}}\n"}, "creationTimestamp": "2019-09-18T15:35:42Z", "finalizers": ["finalizer.secops.pathfinder.gov.bc.ca"], "generation": 2, "name": "inter-namespace-comms", "namespace": "devops-platform-security", "resourceVersion": "374534043", "selfLink": "/apis/secops.pathfinder.gov.bc.ca/v1alpha1/namespaces/devops-platform-security/secopspolicies/inter-namespace-comms/status", "uid": "f96861e8-da29-11e9-a3d8-00505683b471"}, "puid": "e5bc6fbf58e6", "spec": {"action": "Allow", "description": "allow devops-platform-security to talk to itself\n", "destination": "devops-logging", "source": "devops-platform-security"}}, "changed": false}
  |  
  | TASK [Policy Lookup] ***********************************************************
  | task path: /opt/ansible/lookup_netpol.yaml:10
  | changed: [localhost] => {"changed": true, "cmd": "/usr/local/bin/apoctl api list networkaccesspolicies --namespace \"/bcgov/test/lab-pathfinder-091719-01/devops-platform-security\" --filter \"associatedTags contains k8s-uuid=f96861e8-da29-11e9-a3d8-00505683b471\" -c ID,name", "delta": "0:00:06.430109", "end": "2019-09-18 20:34:12.860974", "rc": 0, "start": "2019-09-18 20:34:06.430865", "stderr": "", "stderr_lines": [], "stdout": "- ID: 5d82911a311ddc000175e3cd\n  name: inter-ns-network-87aa1b2c21de", "stdout_lines": ["- ID: 5d82911a311ddc000175e3cd", "  name: inter-ns-network-87aa1b2c21de"]}
  |  
  | TASK [Extract policy attributes] ***********************************************
  | task path: /opt/ansible/lookup_netpol.yaml:19
  | fatal: [localhost]: FAILED! => {"msg": "the field 'args' has an invalid value ({u'policy_id': u'{{ (output.stdout \| from_json \| list \| first).ID }}', u'policy_uuid': u\"{{ ((output.stdout \| from_json \| list \| first).name).split('-')[-1] }}\"}), and could not be converted to an dict.The error was: No JSON object could be decoded\n\nThe error appears to have been in '/opt/ansible/lookup_netpol.yaml': line 19, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  register: output\n- name: Extract policy attributes\n  ^ here\n"}
  |  
  | PLAY RECAP *********************************************************************
  | localhost                  : ok=3    changed=2    unreachable=0    failed=1


```


Here is my cr: 

```
apiVersion: v1
items:
- apiVersion: secops.pathfinder.gov.bc.ca/v1alpha1
  kind: NetworkSecurityPolicy
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"secops.pathfinder.gov.bc.ca/v1alpha1","kind":"NetworkSecurityPolicy","metadata":{"annotations":{},"name":"inter-namespace-comms","namespace":"devops-platform-security"},"spec":{"action":"Allow","description":"allow devops-platform-security to talk to itself\n","destination":"devops-platform-security","source":"devops-platform-security"}}
    creationTimestamp: 2019-09-18T15:35:42Z
    finalizers:
    - finalizer.secops.pathfinder.gov.bc.ca
    generation: 2
    name: inter-namespace-comms
    namespace: devops-platform-security
    resourceVersion: "374535258"
    selfLink: /apis/secops.pathfinder.gov.bc.ca/v1alpha1/namespaces/devops-platform-security/secopspolicies/inter-namespace-comms
    uid: f96861e8-da29-11e9-a3d8-00505683b471
  spec:
    action: Allow
    description: |
      allow devops-platform-security to talk to itself
    destination: devops-logging
    source: devops-platform-security
  status:
    conditions:
    - lastTransitionTime: 2019-09-18T20:34:34Z
      message: Running reconciliation
      reason: Running
      status: "False"
      type: Running
    - ansibleResult:
        changed: 2
        completion: 2019-09-18T20:35:06.642472
        failures: 1
        ok: 3
        skipped: 0
      lastTransitionTime: 2019-09-18T20:35:07Z
      message: |
        the field 'args' has an invalid value ({u'policy_id': u'{{ (output.stdout | from_json | list | first).ID }}', u'policy_uuid': u"{{ ((output.stdout | from_json | list | first).name).split('-')[-1] }}"}), and could not be converted to an dict.The error was: No JSON object could be decoded

        The error appears to have been in '/opt/ansible/lookup_netpol.yaml': line 19, column 3, but may
        be elsewhere in the file depending on the exact syntax problem.

        The offending line appears to be:

          register: output
        - name: Extract policy attributes
          ^ here
      reason: Failed
      status: "True"
      type: Failure
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Comment by jleach** [comment]
@stewartshea Pushed a few small changes - give it a try. In the mean time I'll get admin access to the lab operator and debug there since mine is working as expected.

**Comment by stewartshea** [comment]
Found it @jleach ; the configmap I was using to configure apoctl specified `yaml` as the output and the operator is expecting `json`

**Pull request merged**
