### PR TITLE
Ansible playbook to export policy

### LINKED ISSUE #245: Create YAML import and export mechanics
We need some sort of automation to periodically export all policy in YAML format to a private repository for backup / DR. Importing the policy will likely be done by a person in the event that recovery is needed.

### LINKED ISSUE #385: Deploy Aporeto policy backup script
As a platform-services team member I would like the the backup playbook run periodically so that it automatically builds an audit log of policy changes over time.

Completion

- [ ] Create a private GitHub repository for the policy export and include sufficient documentation in the README.md;
- [ ] Rebuild container to include the backup/export script;
- [ ] Generate SSH deployment keys and Aporeto application token;
- [ ] Schedule a OCP CronJob to run the playbook nightly.

### PR DESCRIPTION
**Pull request by jleach**
This PR creates a playbook that, when run, will:

- Fetch all the relevant namespaces from Aporeto;
- For each namespace, create a matching directory path;
- Export the policy of the given namespace to the newly minted directory.

Fixes #245
Fixes #385

### CODE REVIEW

**Comment by jleach** [comment]
While the playbook runs fine it does take some time:
```console
real    47m57.931s
user    7m32.280s
sys     3m31.330s
```

Most of this time is the `apoctl` command to export the policy for a given namespace. This should be fine if its a nightly batch job but fairly unusable for humans.

**Comment by jleach** [comment]
@stewartshea I was thinking that I'd add this script to the operator image because its has all the Ansible and Aporeto tooling installed. We can just schedule the image to run the playbook as an OCP CronJob.

**Comment by jleach** [comment]
@stewartshea @j-pye I took the WIP sticker of this PR. It works and is ready for review.

**Comment by stewartshea** [comment]
added my initial comments @jleach  -- need some usage docs before we can test.

**Comment by jleach** [comment]
I just added the build and deployment "stuff" I'll pound out some docs and it should be good to go for testing.

**Comment by jleach** [comment]
@stewartshea @j-pye README.md updated with relevant info.

**Comment by jleach** [comment]
This is running in `ak73dc-sandbox`

**Pull request merged**
