### PR TITLE
Improve custom policy name convention

### LINKED ISSUE #283: Improve aporeto object naming convention
Currently objects in Aporeto have a UID fixed to the end of a hard coded string like `custom-netpol-cdf432d`. This should be changed to use the hard coded string concatenated with the custom name chosen by the user. 

Example: `custom-netpol-api2db`

The UID will need to be moved into a metadata tag so that it can be used as part of the import label which will be `j2-template-name-UID`.

### PR DESCRIPTION
**Pull request by jleach**
In the initial version of our operator custom policy uses a hard-coded prefix and an random hex component. This PR improves on this by combining a hard-coded prefix with the name of the k8s object. This allows for the operations team (humans) to correlate the two more easily.

Fixes #283

### CODE REVIEW

**Comment by jleach** [comment]
Thanks @j-pye.

**Comment by stewartshea** [comment]
@jleach This causes a breaking change in the existing environment. Do you think we need a full removal / reapplication of the basic user policies? 

```

TASK [Extract import label part 1] *********************************************
--
  | task path: /opt/ansible/apo_lookup.yaml:33
  | ok: [localhost] => {"ansible_facts": {"tmp_label": "custom-netpol-7d4734b889f7@/bcgov/test/lab-pathfinder-20191001/devops-pipeline-sandbox"}, "changed": false}
  |  
  | TASK [Extract import label part 2] *********************************************
  | task path: /opt/ansible/apo_lookup.yaml:39
  | ok: [localhost] => {"ansible_facts": {"import_label": "custom-netpol-7d4734b889f7"}, "changed": false}
  |  
  | TASK [Found import label] ******************************************************
  | task path: /opt/ansible/apo_lookup.yaml:44
  | ok: [localhost] => {
  | "msg": "Import label custom-netpol-7d4734b889f7"
  | }
  |  
  | TASK [Generate policy ID] ******************************************************
  | task path: /opt/ansible/apo_import.yaml:9
  | changed: [localhost] => {"changed": true, "cmd": ["openssl", "rand", "-hex", "6"], "delta": "0:00:11.454729", "end": "2019-10-01 22:05:49.107599", "rc": 0, "start": "2019-10-01 22:05:37.652870", "stderr": "", "stderr_lines": [], "stdout": "118fbb2a89e2", "stdout_lines": ["118fbb2a89e2"]}
  |  
  | TASK [Extract variables] *******************************************************
  | task path: /opt/ansible/apo_import.yaml:12
  | ok: [localhost] => {"ansible_facts": {"pol_uid": "118fbb2a89e2"}, "changed": false}
  |  
  | TASK [Process j2 template] *****************************************************
  | task path: /opt/ansible/apo_import.yaml:20
  | fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'name'\n\nThe error appears to have been in '/opt/ansible/apo_import.yaml': line 20, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n    pol_uid: \"{{ openssl_cmd.stdout }}\"\n- name: Process j2 template\n  ^ here\n"}
  |  
  |  
  | PLAY RECAP *********************************************************************
  |  
  | PLAY RECAP *********************************************************************
  | localhost                  : ok=9    changed=2    unreachable=0    failed=1


```

It's still running in the lab; I pushed a new image based on your changes. I  won't be able to look at this further until tomorrow.

**Comment by jleach** [comment]
@sheaphillips That's interesting. I'd have to see the policy that's triggering the error. I use `metadata.name` now rather than `spec.name` to construct the Aporeto policy name. I don't think you can have a k8s manifest without a name so I'm not sure why this is complaining.

Also, you might need to delete existing policy from Aporeto and let it re-create it with the proper name. That's one test I didn't think to run.

**Comment by jleach** [comment]
I'm creating some policy with the version on `master` and testing it with the version on this branch.

**Comment by jleach** [comment]
I used the version on master to create some policy then ran the this version and it renamed it correctly - no errors. Some times I find if your run the Ansible operator locally with `operator-sdk up local --kubeconfig=config.yaml --zap-encoder console --namespace ''` it won't pickup changes after an error. I often comment out the `*-main.yaml` code, run the operator, then uncoment and re-run. Then it pickes up my changes and works. Probably not an issue if you're rebuilding the docker image each time.

**Comment by stewartshea** [comment]
I'm definitely rebuilding the operator each time. I don't test locally, I just push to dockerhub and then redeploy. I will remove and reapply all policies in the lab, but the one thing to note is that we will need to think of any other changes that may break in this way before we go live.

**Comment by stewartshea** [comment]
Additional verbosity from the operator. I've removed all policies and am trying to re-apply

```

TASK [Extract variables] *******************************************************
--
  | task path: /opt/ansible/apo_import.yaml:12
  | ok: [localhost] => {
  | "ansible_facts": {
  | "pol_uid": "442963cc124d"
  | },
  | "changed": false
  | }
  |  
  | TASK [Process j2 template] *****************************************************
  | task path: /opt/ansible/apo_import.yaml:20
  | looking for "./templates/custom-netpol.yaml.j2" at "/opt/ansible/templates/./templates/custom-netpol.yaml.j2"
  | looking for "./templates/custom-netpol.yaml.j2" at "/opt/ansible/./templates/custom-netpol.yaml.j2"
  | File lookup using /opt/ansible/./templates/custom-netpol.yaml.j2 as file
  | fatal: [localhost]: FAILED! => {
  | "msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'name'\n\nThe error appears to have been in '/opt/ansible/apo_import.yaml': line 20, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n    pol_uid: \"{{ openssl_cmd.stdout }}\"\n- name: Process j2 template\n  ^ here\n"
  | }
  |  
  | PLAY RECAP *********************************************************************
  | localhost                  : ok=4    changed=2    unreachable=0    failed=1
  |  
  | /tmp/ansible-operator/runner/secops.pathfinder.gov.bc.ca/v1alpha1/NetworkSecurityPolicy/advsol-ops/egress-internet-advsol-ops/artifacts/9136015063997661629//stdout
  | ansible-playbook 2.7.10
  | config file = /etc/ansible/ansible.cfg
  | configured module search path = [u'/usr/share/ansible/openshift']
  | ansible python module location = /usr/lib/python2.7/site-packages/ansible
  | executable location = /usr/bin/ansible-playbook
  | python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
  | Using /etc/ansible/ansible.cfg as config file
  | setting up inventory plugins
  |  
  | /tmp/ansible-operator/runner/secops.pathfinder.gov.bc.ca/v1alpha1/NetworkSecurityPolicy/advsol-ops/egress-internet-advsol-ops/inventory/hosts did not meet host_list requirements, check plugin documentation if this is unexpected
  |  
  | /tmp/ansible-operator/runner/secops.pathfinder.gov.bc.ca/v1alpha1/NetworkSecurityPolicy/advsol-ops/egress-internet-advsol-ops/inventory/hosts did not meet script requirements, check plugin documentation if this is unexpected
  |  
  | Set default localhost to localhost
  | Parsed /tmp/ansible-operator/runner/secops.pathfinder.gov.bc.ca/v1alpha1/NetworkSecurityPolicy/advsol-ops/egress-internet-advsol-ops/inventory/hosts inventory source with ini plugin
  |  
  | statically imported: /opt/ansible/apo_lookup.yaml
  |  
  | statically imported: /opt/ansible/apo_import.yaml
  |  
  | statically imported: /opt/ansible/apo_import.yaml
  | Loading callback plugin awx_display of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible_runner/display_callback/module.pyc
  | /usr/lib/python2.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.24.3) or chardet (2.2.1) doesn't match a supported version!
  | RequestsDependencyWarning)
  |  
  | RequestsDependencyWarning)
  |  
  | PLAYBOOK: netsecpol-main.yaml **************************************************
  | 1 plays in /opt/ansible/netsecpol-main.yaml
  |  
  | PLAY [localhost] ***************************************************************
  | META: ran handlers
  |  
  | TASK [Extract variables] *******************************************************
  | task path: /opt/ansible/netsecpol-main.yaml:8
  | ok: [localhost] => {
  | "ansible_facts": {
  | "metadata": {
  | "annotations": {
  | "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"secops.pathfinder.gov.bc.ca/v1alpha1\",\"kind\":\"NetworkSecurityPolicy\",\"metadata\":{\"annotations\":{},\"name\":\"egress-internet-advsol-ops\",\"namespace\":\"advsol-ops\"},\"spec\":{\"description\":\"allow advsol-ops to talk to the internet\\n\",\"destination\":[[\"ext:network=any\"]],\"source\":[[\"$namespace=advsol-ops\"]]}}\n"
  | },
  | "creationTimestamp": "2019-10-02T15:27:28Z",
  | "finalizers": [
  | "finalizer.secops.pathfinder.gov.bc.ca"
  | ],
  | "generation": 1,
  | "name": "egress-internet-advsol-ops",
  | "namespace": "advsol-ops",
  | "resourceVersion": "391817971",
  | "selfLink": "/apis/secops.pathfinder.gov.bc.ca/v1alpha1/namespaces/advsol-ops/networksecuritypolicies/egress-internet-advsol-ops/status",
  | "uid": "249b08ce-e529-11e9-81f0-00505683b471"
  | },
  | "spec": {
  | "description": "allow advsol-ops to talk to the internet\n",
  | "destination": [
  | [
  | "ext:network=any"
  | ]
  | ],
  | "source": [
  | [
  | "$namespace=advsol-ops"
  | ]
  | ]
  | }
  | },
  | "changed": false
  | }
  |  
  | TASK [Policy Lookup] ***********************************************************
  | task path: /opt/ansible/apo_lookup.yaml:11
  | <localhost> ESTABLISH LOCAL CONNECTION FOR USER: ansible-operator
  | <localhost> EXEC /bin/sh -c 'echo ~ansible-operator && sleep 0'
  | <localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /opt/ansible/.ansible/tmp/ansible-tmp-1570030623.07-46351686714544 `" && echo ansible-tmp-1570030623.07-46351686714544="` echo /opt/ansible/.ansible/tmp/ansible-tmp-1570030623.07-46351686714544 `" ) && sleep 0'
  | Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/_text.py
  | Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/common/__init__.py
  | Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/common/collections.py
  | Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/basic.py
  | Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/six/__init__.py
  | Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/common/_collections_compat.py
  | Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/parsing/convert_bool.py
  | Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/common/file.py
  | Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/parsing/__init__.py
  | Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/pycompat24.py
  | Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/common/process.py
  | Using module file /usr/lib/python2.7/site-packages/ansible/modules/commands/command.py
  | <localhost> PUT /opt/ansible/.ansible/tmp/ansible-local-217pVeYVh/tmpT2NZMn TO /opt/ansible/.ansible/tmp/ansible-tmp-1570030623.07-46351686714544/AnsiballZ_command.py
  | <localhost> EXEC /bin/sh -c 'chmod u+x /opt/ansible/.ansible/tmp/ansible-tmp-1570030623.07-46351686714544/ /opt/ansible/.ansible/tmp/ansible-tmp-1570030623.07-46351686714544/AnsiballZ_command.py && sleep 0'
  | <localhost> EXEC /bin/sh -c '/usr/bin/python /opt/ansible/.ansible/tmp/ansible-tmp-1570030623.07-46351686714544/AnsiballZ_command.py && sleep 0'
  | <localhost> EXEC /bin/sh -c 'rm -f -r /opt/ansible/.ansible/tmp/ansible-tmp-1570030623.07-46351686714544/ > /dev/null 2>&1 && sleep 0'
  | changed: [localhost] => {
  | "changed": true,
  | "cmd": "/usr/local/bin/apoctl api list \"networkaccesspolicies\" --namespace \"/bcgov/test/lab-pathfinder-20191001/advsol-ops\" --filter \"associatedTags contains k8s-uuid=249b08ce-e529-11e9-81f0-00505683b471\" -c ID,associatedTags",
  | "delta": "0:00:13.236853",
  | "end": "2019-10-02 15:37:20.143827",
  | "invocation": {
  | "module_args": {
  | "_raw_params": "/usr/local/bin/apoctl api list \"networkaccesspolicies\" --namespace \"/bcgov/test/lab-pathfinder-20191001/advsol-ops\" --filter \"associatedTags contains k8s-uuid=249b08ce-e529-11e9-81f0-00505683b471\" -c ID,associatedTags",
  | "_uses_shell": true,
  | "argv": null,
  | "chdir": null,
  | "creates": null,
  | "executable": null,
  | "removes": null,
  | "stdin": null,
  | "warn": true
  | }
  | },
  | "rc": 0,
  | "start": "2019-10-02 15:37:06.906974",
  | "stderr": "",
  | "stderr_lines": [],
  | "stdout": "[]",
  | "stdout_lines": [
  | "[]"
  | ]
  | }
  |  
  |  
  | TASK [Extract ID and associatedTags] *******************************************
  |  
  |  
  |  
  | TASK [Extract ID and associatedTags] *******************************************
  | task path: /opt/ansible/apo_lookup.yaml:20
  | skipping: [localhost] => {
  | "changed": false,
  | "skip_reason": "Conditional result was False"
  | }
  |  
  | TASK [Found policy] ************************************************************
  | task path: /opt/ansible/apo_lookup.yaml:29
  | skipping: [localhost] => {}
  |  
  | TASK [Extract import label part 1] *********************************************
  | task path: /opt/ansible/apo_lookup.yaml:33
  | skipping: [localhost] => {
  | "changed": false,
  | "skip_reason": "Conditional result was False"
  | }
  |  
  | TASK [Extract import label part 2] *********************************************
  | task path: /opt/ansible/apo_lookup.yaml:39
  | skipping: [localhost] => {
  | "changed": false,
  | "skip_reason": "Conditional result was False"
  | }
  |  
  | TASK [Found import label] ******************************************************
  | task path: /opt/ansible/apo_lookup.yaml:44
  | skipping: [localhost] => {}
  |  
  | TASK [Generate policy ID] ******************************************************
  | task path: /opt/ansible/apo_import.yaml:9
  | <localhost> ESTABLISH LOCAL CONNECTION FOR USER: ansible-operator
  | <localhost> EXEC /bin/sh -c 'echo ~ansible-operator && sleep 0'
  | <localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /opt/ansible/.ansible/tmp/ansible-tmp-1570030643.28-7807091296911 `" && echo ansible-tmp-1570030643.28-7807091296911="` echo /opt/ansible/.ansible/tmp/ansible-tmp-1570030643.28-7807091296911 `" ) && sleep 0'
  | Using module file /usr/lib/python2.7/site-packages/ansible/modules/commands/command.py
  | <localhost> PUT /opt/ansible/.ansible/tmp/ansible-local-217pVeYVh/tmpLe4GyD TO /opt/ansible/.ansible/tmp/ansible-tmp-1570030643.28-7807091296911/AnsiballZ_command.py
  | <localhost> EXEC /bin/sh -c 'chmod u+x /opt/ansible/.ansible/tmp/ansible-tmp-1570030643.28-7807091296911/ /opt/ansible/.ansible/tmp/ansible-tmp-1570030643.28-7807091296911/AnsiballZ_command.py && sleep 0'
  | <localhost> EXEC /bin/sh -c '/usr/bin/python /opt/ansible/.ansible/tmp/ansible-tmp-1570030643.28-7807091296911/AnsiballZ_command.py && sleep 0'
  | <localhost> EXEC /bin/sh -c 'rm -f -r /opt/ansible/.ansible/tmp/ansible-tmp-1570030643.28-7807091296911/ > /dev/null 2>&1 && sleep 0'
  | changed: [localhost] => {
  | "changed": true,
  | "cmd": [
  | "openssl",
  | "rand",
  | "-hex",
  | "6"
  | ],
  | "delta": "0:00:11.560203",
  | "end": "2019-10-02 15:37:37.504769",
  | "invocation": {
  | "module_args": {
  | "_raw_params": "openssl rand -hex 6",
  | "_uses_shell": false,
  | "argv": null,
  | "chdir": null,
  | "creates": null,
  | "executable": null,
  | "removes": null,
  | "stdin": null,
  | "warn": true
  | }
  | },
  | "rc": 0,
  | "start": "2019-10-02 15:37:25.944566",
  | "stderr": "",
  | "stderr_lines": [],
  | "stdout": "7bcd232b99c7",
  | "stdout_lines": [
  | "7bcd232b99c7"
  | ]
  | }
  |  
  | TASK [Extract variables] *******************************************************
  | task path: /opt/ansible/apo_import.yaml:12
  | ok: [localhost] => {
  | "ansible_facts": {
  | "pol_uid": "7bcd232b99c7"
  | },
  | "changed": false
  | }
  |  
  | TASK [Process j2 template] *****************************************************
  | task path: /opt/ansible/apo_import.yaml:20
  | looking for "./templates/custom-netpol.yaml.j2" at "/opt/ansible/templates/./templates/custom-netpol.yaml.j2"
  | looking for "./templates/custom-netpol.yaml.j2" at "/opt/ansible/./templates/custom-netpol.yaml.j2"
  | File lookup using /opt/ansible/./templates/custom-netpol.yaml.j2 as file
  | fatal: [localhost]: FAILED! => {
  | "msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'name'\n\nThe error appears to have been in '/opt/ansible/apo_import.yaml': line 20, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n    pol_uid: \"{{ openssl_cmd.stdout }}\"\n- name: Process j2 template\n  ^ here\n"
  | }
  |  
  | PLAY RECAP *********************************************************************
  | localhost                  : ok=4    changed=2    unreachable=0    failed=1


```

**Comment by stewartshea** [comment]
I think I know what I did... maybe an idiot tax. I was working out of jleach and you switched to this repo... one sec

**Comment by jleach** [comment]
@stewartshea Just axed my fork.

**Pull request merged**
